{{- if .Values.certificates.requestPolicy.enabled }}
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: {{ include "wazuh.fullname" . }}-node-policy
  annotations:
    "helm.sh/hook": pre-install
spec:
  selector:
    issuerRef:
      name: {{ include "wazuh.fullname" . }}-ca-issuer
  allowed:
    # ── This policy is ONLY for end-entity certs, not for CAs
    isCA: false
    # ── Accept any Common Name (admin, dashboard, node, filebeat, …)
    commonName:
      value: "*"
      required: true
    # ── Subject must match your values.yaml
    subject:
      organizations:
        values:
          - {{ .Values.certificates.subject.organization }}
        required: true
      countries:
        values:
          - {{ .Values.certificates.subject.country }}
        required: true
      localities:
        values:
          - {{ .Values.certificates.subject.locality }}
        required: true
{{- end }}