{{- if .Values.certificates.requestPolicy.enabled }}
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: {{ include "wazuh.fullname" . }}-root-ca-policy
  annotations:
    "helm.sh/hook": pre-install
spec:
  selector:
    issuerRef:
      name: {{ .Values.certificates.issuer.name | default (printf "%s-selfsigned-issuer" (include "wazuh.fullname" .)) }}
      {{- if eq .Values.certificates.issuer.type "ClusterIssuer" }}
      kind: ClusterIssuer
      {{- end }}
  allowed:
    isCA: true
    commonName:
      value: {{ include "wazuh.fullname" . }}-root-ca
      required: true
    subject:
      organizations:
        values:
          - {{ .Values.certificates.subject.organization }}
        required: true
      countries:
        values:
          - {{ .Values.certificates.subject.country }}
        required: true
      localities:
        values:
          - {{ .Values.certificates.subject.locality }}
        required: true
{{- end }}