apiVersion: v1
kind: Service
metadata:
  # Name is only "wazuh" because of Certificates commonName
  name: wazuh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: master
  annotations:
    {{- toYaml .Values.wazuh.master.service.annotations | nindent 4 }}
spec:
  ports:
    - name: registration
      port: {{ .Values.wazuh.master.service.ports.registration.port }}
      targetPort: 1515
      nodePort: {{ .Values.wazuh.master.service.ports.registration.nodePort }}
    - name: api
      port: {{ .Values.wazuh.master.service.ports.api.port }}
      targetPort: 55000
      nodePort: {{ .Values.wazuh.master.service.ports.api.nodePort }}
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: master
  type: {{ .Values.wazuh.master.service.type }}
