apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: worker
  annotations:
    {{- toYaml .Values.wazuh.worker.service.annotations | nindent 4 }}
spec:
  ports:
    - name: agents-events
      port: {{ .Values.wazuh.worker.service.ports.agentEvents.port }}
      targetPort: 1514
      nodePort: {{ .Values.wazuh.master.service.ports.agentEvents.nodePort }}
{{- if .Values.wazuh.syslog_enable }}
    - name: syslog
      port: 514
      targetPort: 514
{{- end }}
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: worker
  type: {{ .Values.wazuh.worker.service.type }}
