apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: worker
  annotations:
    {{- toYaml .Values.wazuh.worker.service.annotations | nindent 4 }}
spec:
  ports:
  {{- range .Values.wazuh.worker.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  {{- if .Values.wazuh.syslog_enable }}
    - name: syslog
      port: 514
      targetPort: 514
  {{- end }}
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: worker
  type: {{ .Values.wazuh.worker.service.type }}
